# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patent < Formula
  desc "Patent Connector CLI - patent/trademark tools, against a server or in-process"
  homepage "https://patent.dev"
  version "1.7.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.patent.dev/patent_1.7.10_darwin_amd64.tar.gz"
      sha256 "4eaf446162ea699b6fba281979a2fa40161e50317bd316c03c6789af2b6ada9d"

      define_method(:install) do
        bin.install "patent"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.patent.dev/patent_1.7.10_darwin_arm64.tar.gz"
      sha256 "8a74b09f5a75e83e82e0061c51d45bf8876be8afdb87e5ab8c1ca0b80e2a73da"

      define_method(:install) do
        bin.install "patent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.patent.dev/patent_1.7.10_linux_amd64.tar.gz"
      sha256 "d92ae3d7b3cb23942815d1e9dc98b60e18a432be21cce8e712a1e53ab10f2130"
      define_method(:install) do
        bin.install "patent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.patent.dev/patent_1.7.10_linux_arm64.tar.gz"
      sha256 "84c072ba8e953313006e8e4a038c6a906b2a78cf4bc1aac1ea5670db06e73f71"
      define_method(:install) do
        bin.install "patent"
      end
    end
  end
end
