# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patent < Formula
  desc "Patent Connector CLI - patent/trademark tools, against a server or in-process"
  homepage "https://patent.dev"
  version "1.7.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://get.patent.dev/patent_1.7.14_darwin_amd64.tar.gz"
      sha256 "5f7a94a3b9a38a15a3efbf8e438b237eaa6db161a7a2dfad972688baadebcc9a"

      define_method(:install) do
        bin.install "patent"
      end
    end
    if Hardware::CPU.arm?
      url "https://get.patent.dev/patent_1.7.14_darwin_arm64.tar.gz"
      sha256 "157502efa070807cb75c53d3357857bb5edfb67b1d14728b3ecc86009f3d7c19"

      define_method(:install) do
        bin.install "patent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://get.patent.dev/patent_1.7.14_linux_amd64.tar.gz"
      sha256 "8dbb97ab7d0819ba0d75a77ccb5167a2dd718365f75e8aa693088fd311bc023e"
      define_method(:install) do
        bin.install "patent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://get.patent.dev/patent_1.7.14_linux_arm64.tar.gz"
      sha256 "fb34bc77dfac29fa6723c0581818667de175ce3454c0b9f72fb948481e9a468f"
      define_method(:install) do
        bin.install "patent"
      end
    end
  end
end
